version: "3"

volumes:
  postgresql-volume:  # pointing volume to db

services:
  djangoapp:
    depends_on:
      - db
    build: ./djangoapp
    volumes:
      - ./djangoapp:/djangoapp  # djangoapp mounted to docker from current directory
      - ./djangoapp/static:/static # adding static & media file for django
      - ./djangoapp/media:/media
    command: ./djangoapp/entrypoint.sh # execute bashfile we've created before

  db:
    image: postgres:10.1  # install postgre here
    volumes:
      - postgresql-volume:/var/lib/postgresql/data # avoid data removal when shut docker down we put volume in our local
