version: "3"

services:
  djangoapp:
    depends_on:
      - db
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/djangoapp
      - ./static:/static
      - ./media:/media
    command: ./entrypoint.sh

  db:
    image: postgres:10.1
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  postgresql-volume:
